### ISSUE TITLE
Cannot compile CLI due to compile errors in PIG module

### ISSUE THREAD

**Issue by jbartece** [project-ncl/cli#42]
[jbartece@localhost cli]$ mvn clean install
......

[INFO] 21 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] parent ............................................. SUCCESS [  0.373 s]
[INFO] auth ............................................... SUCCESS [  9.414 s]
[INFO] common ............................................. SUCCESS [ 16.694 s]
[INFO] config ............................................. SUCCESS [  0.747 s]
[INFO] da ................................................. SUCCESS [  1.745 s]
[INFO] pnc ................................................ SUCCESS [  0.901 s]
[INFO] test-common ........................................ SUCCESS [  0.042 s]
[INFO] pig ................................................ FAILURE [ 50.442 s]
[INFO] cli ................................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:20 min
[INFO] Finished at: 2019-08-27T12:56:54+02:00
[INFO] Final Memory: 53M/701M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project pig: Compilation failure: Compilation failure:
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java:[118,80] incompatible types: java.lang.String cannot be converted to java.lang.Integer
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncConfigurator.java:[76,47] incompatible types: java.lang.String cannot be converted to int
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncConfigurator.java:[88,67] incompatible types: java.lang.String cannot be converted to int
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java:[176,27] incompatible types: inference variable T has incompatible bounds
[ERROR] equality constraints: java.lang.Integer
[ERROR] lower bounds: java.lang.String
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java:[211,81] incompatible types: java.lang.String cannot be converted to int
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java:[212,24] invalid method reference
[ERROR] non-static method getId() cannot be referenced from a static context
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java:[221,67] incompatible types: java.lang.String cannot be converted to int
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java:[229,64] incompatible types: java.lang.String cannot be converted to int
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java:[286,47] incompatible types: java.lang.String cannot be converted to java.lang.Integer
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java:[310,47] incompatible types: java.lang.Integer cannot be converted to java.lang.String
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java:[434,94] incompatible types: java.lang.String cannot be converted to int
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java:[537,78] incompatible types: java.lang.String cannot be converted to int
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildConfigData.java:[51,29] incompatible types: java.lang.String cannot be converted to java.lang.Integer
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/script/ScriptGenerator.java:[88,53] incompatible types: java.lang.String cannot be converted to java.lang.Integer
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java:[50,75] incompatible types: java.lang.String cannot be converted to int
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java:[77,49] incompatible types: java.lang.String cannot be converted to int
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java:[78,86] incompatible types: java.lang.String cannot be converted to int
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java:[51,47] incompatible types: java.lang.String cannot be converted to int
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java:[64,54] incompatible types: java.lang.String cannot be converted to int
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java:[259,25] incompatible types: inference variable T has incompatible bounds
[ERROR] equality constraints: java.lang.Integer
[ERROR] lower bounds: java.lang.String
[ERROR] /home/jbartece/projects/pnc/cli/pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java:[266,63] incompatible types: java.lang.String cannot be converted to int
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pig

**Comment by jbartece** [comment]
It is most probably due to 7fd757b4cc64da3e469d61009dda34c6c8a3126b "[NCL-4872] Change REST DTOs to use String ids" committed by @thescouser89 to PNC yesterday

**Comment by jbartece** [comment]
When compiling bacon with PNC built from commit before the mentioned one, it compiles

**Comment by thescouser89** [comment]
Should be resolved now.
